### ISSUE TITLE
Friday todo list 

### ISSUE THREAD

**Issue by pastika** [susy2015/StopTupleMaker#18]
- Add explicit Pt cut to AK4 & 8 jets in ProdJets
- Add deepAK8 variables to treeMaker in python configuration file 
- Add cddpCSVBvvsAll variables to treeMaker in python configuration file

**Comment by pastika** [comment]
@scarletnorberg What is the status of theses?

**Comment by scarletnorberg** [comment]
This is in my code once I update to the new branch and make sure things run than I can close this.

**Comment by scarletnorberg** [comment]
Done.
