### ISSUE TITLE
Update Gen Photon Status Code

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/StopTupleMaker#19]
I think we decided to only use status = 1 for gen photons.

https://github.com/susy2015/StopTupleMaker/blob/41fc3a9f378aeda691af9f5aac55489dfb632b55/SkimsAUX/plugins/PhotonIDisoProducer.cc#L186-L187

For reference, here is the twiki for Pythia particle status codes: http://home.thep.lu.se/~torbjorn/pythia81html/ParticleProperties.html

**Comment by pastika** [comment]
@scarletnorberg @caleb-james-smith This seems implemented, if I am correct close the issue

**Comment by caleb-james-smith** [comment]
I noticed that it was not implemented on the master branch, which is why I made the issue recently. I can make a PR to fix it...

**Comment by scarletnorberg** [comment]
Please do not. IT is already in my new fix but because master was not working I have not pushed the changes I made recently in my code. It will be pushed soon.

**Comment by caleb-james-smith** [comment]
Ok.

**Comment by scarletnorberg** [comment]
Done.

**Comment by caleb-james-smith** [comment]
When are you planning to make a PR with the fix for the master branch?
