### ISSUE TITLE
DeepAK8

### ISSUE THREAD

**Issue by scarletnorberg** [susy2015/StopTupleMaker#20]
git clone ssh://git@gitlab.cern.ch:7999/TreeMaker/NNKit.git -b cmssw-improvements-4

scram setup /cvmfs/cms.cern.ch/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_3_0_pre4/config/toolbox/slc6_amd64_gcc700/tools/selected/mxnet-predict.xml

**Comment by pastika** [comment]
@scarletnorberg can you put these in the readme and add it to my PR?
