### ISSUE TITLE
NNKit/FatJetNN/interface/FatJetNN.h?

### ISSUE THREAD

**Issue by hatakeyamak** [susy2015/StopTupleMaker#21]
I tried to run the most recent recipe under CMSSW_9_4_10 and got these errors. Probably related to the post by Scarlet, but writing there for record.

/uscms_data/d2/hatake/HadronicStop/CMSSW_9_4_10_LPC/src/StopTupleMaker/SkimsAUX/plugins/prodJets.cc:25:47: fatal error:NNKit/FatJetNN/interface/FatJetNN.h: No such file or directory
 #include "NNKit/FatJetNN/interface/FatJetNN.h"
                                               ^
compilation terminated.
>> Compiling edm plugin /uscms_data/d2/hatake/HadronicStop/CMSSW_9_4_10_LPC/src/StopTupleMaker/SkimsAUX/plugins/prodGoodVertices.cc 
>> Compiling edm plugin /uscms_data/d2/hatake/HadronicStop/CMSSW_9_4_10_LPC/src/StopTupleMaker/SkimsAUX/plugins/genDecayStringMakerPythia8.cc 
>> Compiling edm plugin /uscms_data/d2/hatake/HadronicStop/CMSSW_9_4_10_LPC/src/StopTupleMaker/SkimsAUX/plugins/provInfo.cc 
/uscms_data/d2/hatake/HadronicStop/CMSSW_9_4_10_LPC/src/StopTupleMaker/SkisAUX/plugins/prodJets.cc:25:47: fatal error:NNKit/FatJetNN/interface/FatJetNN.h: No such file or directory
 #include "NNKit/FatJetNN/interface/FatJetNN.h"

**Comment by hatakeyamak** [comment]
Indeed looks like two lines from
https://github.com/susy2015/StopTupleMaker/issues/20
address this error.
These should be a part of README ?

Also I had to comment out one line to avoid:
/uscms_data/d2/hatake/HadronicStop/CMSSW_9_4_10_LPC/src/StopTupleMaker/SkimsAUX/plugins/prodElectrons.cc:23:67: fatal error: StopTupleMaker/SkimsAUX/plugins/ElectronEffectiveArea.h: No such file or directory
 #include "StopTupleMaker/SkimsAUX/plugins/ElectronEffectiveArea.h"

**Comment by scarletnorberg** [comment]
Yes this ElectronEffectiveArea is a recently known issue and is being fixed.

**Comment by hatakeyamak** [comment]
ok.

**Comment by pastika** [comment]
sorry about the forgotten files, they are now replaced into the repository (ElectronEffectiveArea.h and 3 others).  See the new PR to get these changes.

**Comment by hatakeyamak** [comment]
No problem at all. Thank you for addressing this quickly.
Now it compiles, but I still cannot run it.

cd StopTupleMaker/SkimsAUX/workdir/prod
cmsRun treeMaker_stopRA2.py
...
----- Begin Fatal Exception 31-Oct-2018 09:32:11 CDT-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named treeMaker_stopRA2.py
Exception Message:
python encountered the error: <type 'exceptions.KeyError'>
'ptThreshold'
----- End Fatal Exception -------------------------------------------------

**Comment by hatakeyamak** [comment]
ok.
fixEE2017Params = {'userawPt': True, 'PtThreshold':50.0, 'MinEtaThreshold':2.65, 'MaxEtaThreshold': 3.139} ,
needs to be:
   fixEE2017Params = {'userawPt': True, 'ptThreshold':50.0, 'minEtaThreshold':2.65, 'maxEtaThreshold': 3.139} ,
and this is the mistake from the original twiki. Can this be updated in your PR?

**Comment by pastika** [comment]
Thanks for the careful feedback ken! I am closing this issue now that it is addressed in the new PR

**Comment by hatakeyamak** [comment]
Thx.
