### ISSUE TITLE
Adding wget for data base files

### ISSUE THREAD

**Issue by scarletnorberg** [susy2015/StopTupleMaker#27]
Just copy link from twiki page and put wget in front should work. Ask Joe where the Quark Gluon file came from because can not remember that twiki page.

**Comment by pastika** [comment]
https://github.com/cms-jet/QGLDatabase/tree/master/SQLiteFiles

this is where these files come from, but I am trying to determine if it is even needed.

**Comment by pastika** [comment]
It seems that the version of this file in the global tags is the same as the version we add by hand, and the this file was last updated in the global tag in 2015, so I think we are safe to use the version in the GT.
