### ISSUE TITLE
Jet collection has no JEC applied

### ISSUE THREAD

**Issue by pastika** [susy2015/StopTupleMaker#29]
We see this message in the output of the current master branch 

```
%MSG-w L3Absolute not found:  PATJetUpdater:updatedPatJetsAK4PFCHS  01-Nov-2018 19:49:38 CDT Run: 1 Event: 138712468
L2L3Residual and L3Absolute are not part of the jetCorrFactors
of module patJetCorrFactorsAK4PFCHS. Jets will remain uncorrected.
%MSG
```

Looking at the Ntuples I confirm that we really are not getting any JECs applied to the nominal jet collection.  The lepton cleaned jet collection however appears to be OK.  Looking at the results of edmConfigDump I see the following 

```
process.patJetCorrFactorsAK4PFCHS = cms.EDProducer("JetCorrFactorsProducer",
    emf = cms.bool(False),
    extraJPTOffset = cms.string('L1FastJet'),
    flavorType = cms.string('J'),
    levels = cms.vstring(),
    payload = cms.string('AK4PFchs'),
    primaryVertices = cms.InputTag("offlineSlimmedPrimaryVertices"),
    rho = cms.InputTag("fixedGridRhoFastjetAll"),
    src = cms.InputTag("slimmedJets"),
    useNPV = cms.bool(True),
    useRho = cms.bool(True)
)


process.patJetCorrFactorsAK4PFCHSNoLep = cms.EDProducer("JetCorrFactorsProducer",
    emf = cms.bool(False),
    extraJPTOffset = cms.string('L1FastJet'),
    flavorType = cms.string('J'),
    levels = cms.vstring('L1FastJet',
        'L2Relative',
        'L3Absolute'),
    payload = cms.string('AK4PFchs'),
    primaryVertices = cms.InputTag("offlineSlimmedPrimaryVertices"),
    rho = cms.InputTag("fixedGridRhoFastjetAll"),
    src = cms.InputTag("ak4PFJetsCHSNoLep"),
    useNPV = cms.bool(True),
    useRho = cms.bool(True)
)
```

Notice that for some reason the "levels" of the nominal jet collection is blank.  This is strange as the same jet energy correction information is passed to both collections [1].  The only difference between the two is that the nominal jets are produced with "updateJetCollection" while the lepton cleaned jets are produced with "addJetCollection".  However these both call the exact same function used to update the JEC for the jets [2].  

[1] https://github.com/susy2015/StopTupleMaker/blob/master/SkimsAUX/workdir/treeMaker_stopRA2.py#L220-L250

[2] https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_X/PhysicsTools/PatAlgos/python/tools/jetTools.py#L1728

https://github.com/cms-sw/cmssw/blob/CMSSW_9_4_X/PhysicsTools/PatAlgos/python/tools/jetTools.py#L1232

**Comment by scarletnorberg** [comment]
This is also what I see. We always used JetToolBox for everything so we have never seen this error. Since the BJets DeepCSV are already included in 94X I agree that we should do just the JEC's.

**Comment by scarletnorberg** [comment]
I would point out that this is causing another wrinkle in going back and forth from 80X and 94X because we will need to include the DeepCSV because they do not come as default in 80X jet collections.

**Comment by pastika** [comment]
Addressed in https://github.com/susy2015/StopTupleMaker/pull/30
