### ISSUE TITLE
Requesting Variables Update for "CMSSW8028_2016" production 

### ISSUE THREAD

**Issue by zhenbinwu** [susy2015/StopTupleMaker#3]
This issue will be used to keep track of requests for the variables update from "CMSSW8028_2016" production. The updates are expected for next MC production.

**Comment by zhenbinwu** [comment]
Change qgMult to float instead of int, which is needed for the top tagger code to avoid conversion 
https://github.com/susy2015/SusyAnaTools/blob/AddNewTagger/Tools/baselineDef.cc#L144-L146

**Comment by kencall** [comment]
Include prodJetsNoLep_recoJetsFlavor

**Comment by zhenbinwu** [comment]
DeepCSVxxN and DeepCSVxxP are from the nagetive/positive DeepFlavourJetTag, which is wrong. 
https://github.com/susy2015/StopTupleMaker/blob/94X_intermediate_Branch_works/SkimsAUX/python/prodJets_cfi.py#L35-L36

**Comment by caleb-james-smith** [comment]
Variable name changes moving from SoftBjet_PhotonNtuples to CMSSW8028_2016 ntuples
```
recoJetsBtag_0              ---> recoJetsCSVv2
recoJetsBtag_0_LepCleaned   ---> prodJetsNoLep_recoJetsCSVv2
looseJetID                  ---> AK4looseJetID
looseJetID_NoLep            ---> AK4NoLeplooseJetID
jetsLVecLepCleaned          ---> prodJetsNoLep_jetsLVec
recoJetsJecUncLepCleaned    ---> prodJetsNoLep_recoJetsJecUnc
nJets                       ---> nJets_CUT
softDropMass                ---> puppisoftDropMass
ak8JetsLVec                 ---> puppiJetsLVec
Removed deepAK8LVec
```

**Comment by zhenbinwu** [comment]
@caleb-james-smith These name are OK right? This issue is to keep track of what should be changed in the next ntuple production, from CMSSW8028_2016 to XX.

**Comment by caleb-james-smith** [comment]
Ah, ok. Yes, these names are good. They are just what what changed in moving from SoftBjet_PhotonNtuples to CMSSW8028_2016.

**Comment by scarletnorberg** [comment]
Also not sure why this was not close but I think it is done.
