### ISSUE TITLE
PhotonIDs are Always Tight

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/StopTupleMaker#5]
The photon ids are always loose! They should be loose, medium, and tight.

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/workdir/prod/treeMaker_stopRA2.py#L870-L877

**Comment by scarletnorberg** [comment]
Issue fixed.

**Comment by caleb-james-smith** [comment]
Thanks @scarletnorberg . Can you push your fix to the CMSSW8028Patch1_2016 branch?

https://github.com/susy2015/StopTupleMaker/tree/CMSSW8028Patch1_2016
