### ISSUE TITLE
Problem with PhotonID

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/StopTupleMaker#6]
This issue may not be relevant if we will never use fullID and extraLooseID for photons...

Nevertheless, I noticed subtle differences between the isolation implementation and the twiki. This could explain some of the strange features that we observed for extraLooseID. I cannot test the fullID because we don't store it in the ntuples at the moment.

Implementation:

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L312-L328

Twiki: https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2#Offline_selection_criteria

There should not be an exponent on these two lines:

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L314

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L317

The factor 0.0119 should only multiply the linear pt() term these two lines:

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L325

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L325

**Comment by scarletnorberg** [comment]
For 2016 the IDs are correct so for your test you are fine. But you are correct in 2017 this did get removed and change. I had not changed it yet or removed it because I think we were debating weather we are using it or not.

**Comment by caleb-james-smith** [comment]
I found the issue for the https://github.com/susy2015/StopTupleMaker/tree/CMSSW8028Patch1_2016 branch. We can close the issue if we don't want to use the photon ids.

**Comment by caleb-james-smith** [comment]
I also see the issue for the https://github.com/susy2015/StopTupleMaker/tree/CMSSW946_patch1 branch.

**Comment by pastika** [comment]
@caleb-james-smith Is this fixed?

**Comment by scarletnorberg** [comment]
I think so. I was just thinking I should close the ones that I know are done today.

**Comment by caleb-james-smith** [comment]
The old photon IDs are removed form the master branch, which is good. The old IDs (with the inconsistencies I have noted) is still present in the CMSSW8028Patch1_2016 branch, but is commented out. At this stage we can close the issue.
