### ISSUE TITLE
Photons should be 2016 for 2016

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/StopTupleMaker#7]
Why are 2017 photons used for 2016? 

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/python/PhotonIDisoProducer_cfi.py#L11-L13

It is also confusing that these are different compared to what is listed here.

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/workdir/prod/treeMaker_stopRA2.py#L870-L877

**Comment by pastika** [comment]
The cuts in "cfi" filse are basically defaults.  You see here in the cfg file that they are being overridden.  You should always be on the look out for this with all cmssw modules.

**Comment by caleb-james-smith** [comment]
Ok, fair enough.
