### ISSUE TITLE
Filling Reco Photons (gammaLVec)

### ISSUE THREAD

**Issue by caleb-james-smith** [susy2015/StopTupleMaker#8]
At the moment, the reco photons vector (gammaLVec ) is filled without the passAcc requirement, but other related variables are will with the passAcc requirement (loosePhotonID, mediumPhotonID, tightPhotonID).

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L178-L185

https://github.com/susy2015/StopTupleMaker/blob/aae2e68dd08aacc5fe5f73a8ba48fb714f5a2525/SkimsAUX/plugins/PhotonIDisoProducer.cc#L332-L354

It would be more straightforward if gammaLVec was filled in the same place (in the same loop) and with the same requirements.

**Comment by caleb-james-smith** [comment]
This commit doesn't fix the issue because the passAcc variable conditions wherehttps://github.com/susy2015/StopTupleMaker/commit/9ed857c2143dea45b834d8984ba39c81777af77b#diff-a6f9adfca3eedbd92b4c2ad6faf0d29eL292

**Comment by pastika** [comment]
@caleb-james-smith What is the status of this issue?

**Comment by scarletnorberg** [comment]
This has been done in both 80 and 94 and not sure why it had not been closed. But done!

**Comment by caleb-james-smith** [comment]
Yep, it is done.
